// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDWVentas.Models.DwVentas.ModelsVentas;

public partial class DwVentasContext : DbContext
{
    public DwVentasContext(DbContextOptions<DwVentasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactClienteAtendido> FactClienteAtendidos { get; set; }

    public virtual DbSet<FactOrder> FactOrders { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactClienteAtendido>(entity =>
        {
            entity.HasKey(e => e.ClienteAtendidoId);

            entity.ToTable("FactClienteAtendido");

            entity.Property(e => e.TotalClientes)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        modelBuilder.Entity<FactOrder>(entity =>
        {
            entity.HasKey(e => e.OrderNumber);

            entity.ToTable("FactOrder");

            entity.Property(e => e.City)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CustumerKey)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}