// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWVentas.Models.DwVentas.ModelsVentas;

public partial class FactClienteAtendido
{
    public int ClienteAtendidoId { get; set; }

    public int EmployeeKey { get; set; }

    public string TotalClientes { get; set; }
}