// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewOrdenesEnviadasPorTransportistum
{
    public int ShipperId { get; set; }

    public string Transportista { get; set; }

    public int? NumeroOrdenes { get; set; }
}