// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewOrdenesPorCliente
{
    public string CustomerId { get; set; }

    public string Cliente { get; set; }

    public int? NumeroOrdenes { get; set; }
}