// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewProduct
{
    public string Name { get; set; }

    public string Description { get; set; }

    public short? Inventory { get; set; }

    public decimal? SellingPrice { get; set; }
}