// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewVentasPorRegionPai
{
    public string ShipCountry { get; set; }

    public int? Cantidad { get; set; }
}