// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewProductosMasVendido
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? CantidadVendida { get; set; }
}