// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Models;

public partial class ViewProductividadEmpleado
{
    public int EmployeeId { get; set; }

    public string Empleado { get; set; }

    public decimal? TotalVentas { get; set; }
}