// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Entities;

public partial class DimCustumer
{
    public int CustomerKey { get; set; }

    public string CustumerName { get; set; }
}