// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Entities;

public partial class DimProductCategory
{
    public int ProductKey { get; set; }

    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public string ProductName { get; set; }

    public string CategoryName { get; set; }
}