// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Entities;

public partial class DimShipper
{
    public int ShipperId { get; set; }

    public string CompanyName { get; set; }
}