// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Entities;

public partial class FactOrder
{
    public int OrderNumber { get; set; }

    public int DateKey { get; set; }

    public int ProductKey { get; set; }

    public int EmployeeKey { get; set; }

    public int ShipperKey { get; set; }

    public int CustumerKey { get; set; }

    public string City { get; set; }

    public decimal TotalVentas { get; set; }

    public int CantidadVentas { get; set; }
}