// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDWVentas.Models.Models;

public partial class DbSalesContext : DbContext
{
    public DbSalesContext(DbContextOptions<DbSalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Vwventa> Vwventas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Vwventa>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VWVentas", "DWH");

            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.CustomerId)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("CustomerID");
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(40);
            entity.Property(e => e.EmpleyeeName)
                .IsRequired()
                .HasMaxLength(31);
            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.ShipperId).HasColumnName("ShipperID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}