// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using cargaDwhVenta.ObjetoBaseDatos.Context;
using cargaDwhVenta.ObjetoBaseDatos.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Context.Configurations
{
    public partial class DimDateConfiguration : IEntityTypeConfiguration<DimDate>
    {
        public void Configure(EntityTypeBuilder<DimDate> entity)
        {
            entity.HasKey(e => e.DateKey);

            entity.ToTable("DimDate");

            entity.Property(e => e.DateName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MonthName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.YearName)
                .HasMaxLength(50)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimDate> entity);
    }
}
