// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using cargaDwhVenta.ObjetoBaseDatos.Context;
using cargaDwhVenta.ObjetoBaseDatos.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Context.Configurations
{
    public partial class DimShipperConfiguration : IEntityTypeConfiguration<DimShipper>
    {
        public void Configure(EntityTypeBuilder<DimShipper> entity)
        {
            entity.HasKey(e => e.ShipperId);

            entity.ToTable("DimShipper");

            entity.Property(e => e.ShipperId).HasColumnName("ShipperID");
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DimShipper> entity);
    }
}
