// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using cargaDwhVenta.ObjetoBaseDatos.Context;
using cargaDwhVenta.ObjetoBaseDatos.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Context.Configurations
{
    public partial class FactOrderConfiguration : IEntityTypeConfiguration<FactOrder>
    {
        public void Configure(EntityTypeBuilder<FactOrder> entity)
        {
            entity.HasKey(e => e.OrderNumber);

            entity.ToTable("FactOrder");

            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TotalVentas).HasColumnType("decimal(18, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactOrder> entity);
    }
}
