// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using cargaDwhVenta.ObjetoBaseDatos.Context;
using CargaDwhVenta.Dato.Entities.DwVentas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace cargaDwhVenta.ObjetoBaseDatos.Context.Configurations
{
    public partial class FactClienteAtendidoConfiguration : IEntityTypeConfiguration<FactClienteAtendido>
    {
        public void Configure(EntityTypeBuilder<FactClienteAtendido> entity)
        {
            entity.HasKey(e => e.ClienteAtendidoId);

            entity.ToTable("FactClienteAtendido");

            entity.Property(e => e.TotalClientes)
                .HasMaxLength(10)
                .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactClienteAtendido> entity);
    }
}
