// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CargaDwhVenta.Dato.Entities.DwVentas;

public partial class ViewTotalVentasPorCliente
{
    public string CustomerId { get; set; }

    public string Cliente { get; set; }

    public decimal? TotalVentas { get; set; }
}