// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CargaDwhVenta.Dato.Entities.DwVentas;

public partial class ViewPedidosProcesadosPorEmpleado
{
    public int EmployeeId { get; set; }

    public string Empleado { get; set; }

    public int? NumeroPedidos { get; set; }
}