// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CargaDwhVenta.Dato.Entities.DwVentas;

public partial class ViewProductosMasVendidosPorCategorium
{
    public string CategoryName { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? CantidadVendida { get; set; }
}